### ISSUE TITLE
Reports that internet connection has failed, when it is working

### ISSUE THREAD

**Issue by mbabuskov** [tdulcet/Remote-Servers-Status#1]
Hi,

I'm trying to run this on CentOS and it fails because it has no ping4 command.

I find it strange that it uses ping4 to check internet availability but it later uses regular ping command for ping test. Perhaps it should be configurable or at least use the same command in both places and we can create alias for the script.

**Comment by tdulcet** [comment]
It uses both the `ping4` and `ping6` commands so it can separately test for IPv4 and IPv6 connectivity respectively:
https://github.com/tdulcet/Remote-Servers-Status/blob/1106b1168f06b84e08cc87722cb19ac1282a6501/status.sh#L212-L221

Are you not able to install these two commands in CentOS? If so, I could potentially just switch out them with `ping -4` and `ping -6` respectively.

**Comment by mbabuskov** [comment]
CentOS doesn't have ping4 command:

    $ yum provides ping4
    No matches found

I think "ping" defaults to IPv4 and "ping6" is when you want IPv6 explicitly. I don't mind how you solve it.

**Comment by tdulcet** [comment]
OK, thanks for the information. I just pushed my above proposed fix in https://github.com/tdulcet/Remote-Servers-Status/commit/85452614745e299c7a853f99a84a1f5da3292752.
