### ISSUE TITLE
Checks that use indexOf fail on CentOS 7

### ISSUE THREAD

**Issue by mbabuskov** [tdulcet/Remote-Servers-Status#2]
I had a bunch of commands fail (for example Domain expiry check) because "local" in CentOS bash doesn't have -n option:

    local: -n: invalid option

I tried to find some workaround but my shell-fu isn't up to par. Any idea how to work around it or rewrite indexof() function to work without -n support?

**Comment by tdulcet** [comment]
The script requires Bash 4.3+, so as stated on the README, make sure you either run it with: `./status.sh` or explicitly use Bash: `bash status.sh`. If you are using Bash, what is the output of `echo "$BASH_VERSION"`?

**Comment by mbabuskov** [comment]
4.2.46(2)-release

**Comment by mbabuskov** [comment]
Hm, make you could add a check at script startup and bail out?

**Comment by mbabuskov** [comment]
BTW, bash 4.2 version is used by CentOS 7.x which has active LTS support until July 2024 so there are a lot of servers running it by default.

**Comment by tdulcet** [comment]
Interesting, Bash 4.2 is [from 2011](https://en.wikipedia.org/wiki/Bash_(Unix_shell)#Release_history), so I am surprised that it is still supported by anyone... Most of my other scripts already require at least Bash 4.4. Anyway, it is of course possible to update this function to use the [old syntax](https://github.com/dylanaraps/pure-bash-bible#assign-and-access-a-variable-using-a-variable), but there might be other incompatibilities with Bash 4.2 in the script.

**Edit**: From further looking at it, there actually is some Bash 4.4 syntax in the script, so you would also need to revert my changes in https://github.com/tdulcet/Remote-Servers-Status/commit/1106b1168f06b84e08cc87722cb19ac1282a6501, specifically those that added the `@E` and `@Q`s.

**Comment by mbabuskov** [comment]
This thing with RHEL and derivatives like CentOS / Rocky Linux is that they usually ship with stable (i.e. a couple years old packages) when the distro is new and then they support it for around 10 years. So, you get 10-15 year old software near the end of the cycle. 

However, they apply all security patches to it, so you basically have a stable feature set and security in the long run.

Thanks for checking for other incompatibilities. I will look into patching the script or maybe running it on another server with newer Rocky Linux installation instead.

**Comment by tdulcet** [comment]
Thanks for the info. I usually try to support the oldest version of Debian/Ubuntu that is still officially supported. Currently that is Ubuntu 18.04 LTS, which includes Bash 4.4. I will definitely update the README to make this clearer.

Anyway, I am open to supporting older Bash versions, so PRs are welcome. However, I am of course not committing to supporting those older versions indefinitely, as I do not have access to any systems that old to test it on, although July 2024 would be fine

The necessary changes to the `indexOf()` function and to remove that parameter transformation syntax should be simple. Also see: https://unix.stackexchange.com/q/486461.

**Comment by tdulcet** [comment]
I removed the `indexOf()` function as part of 8115c550e4c748db4143169d6c9df70b76ef2af5, so the script should now work for you. Let me know if you have any further issues.
