### ISSUE TITLE
fails on spamhaus checks

### ISSUE THREAD

**Issue by jult** [tdulcet/Remote-Servers-Status#3]
```
Error querying whois server: connect: Connection refused
                ⚠🚫 Warning: The domain is listed in the 'dbl.spamhaus.org' blacklist (127.255.255.254): "Error: open resolver; https://www.spamhaus.org/returnc/pub/198.41.241.17".
                ⚠🚫 Warning: The IP address (xxx.xxx.xxx.xxx) is listed in the 'zen.spamhaus.org' blacklist (127.255.255.254): "Error: open resolver; https://www.spamhaus.org/returnc/pub/198.41.241.67".


```
both are not true. I've checked at https://check.spamhaus.org/not_listed/?searchterm=xxx.xxx.xxx.xxx
We're not an open resolver. Never have been. The IP4 address mentioned at the end of the spamhaus URL is unknown to me.
Same goes for the zen.spamhaus check..

**Comment by tdulcet** [comment]
Thanks for the bug report. This script uses a pubic DNS resolver by default (see the `DNS` variable near the top of the script to change this), as many local DNS servers do not support DNSSEC. However, it looks like Spamhaus no longer supports using public DNS resolvers to check their blacklist and now returns this error. DNS blacklists return error codes in the form of an IP address, which typically means the IP address or domain is blacklisted. Anyway, I will update the script to use the local DNS server instead when checking the blacklists, which should resolve this issue for most users.

Note that from your provided output, I see the `whois` command used for the domain monitoring also failed. As you may know, not all TLDs have a working whois server, so this is likely to be expected for whatever domain you are monitoring. However, if you believe this is an error, please let me know...

**Comment by jult** [comment]
Strangely, the TLD is .org, so that should not be an issue..
-- It was the firewall. Had to open tcp port 43 outwards.
